create database customer_data;
use customer_data;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount)  from customer_behavior
group by gender
order by sum(purchase_amount) desc;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id , purchase_amount from customer_behavior
where discount_applied is not null
and purchase_amount > (select avg(purchase_amount) from customer_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased as 'products', round(avg(review_rating),2) as 'top 5'
from customer_behavior
group by products
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(avg(purchase_amount),2)
from customer_behavior
where shipping_type in ("Standard", "Express")
group by shipping_type; 

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status, 
       COUNT(customer_id) AS total_customers, ROUND(AVG(purchase_amount),2) as 'average_spend' ,
       ROUND(SUM(purchase_amount),2) as 'total_spend'
from customer_behavior
group by subscription_status
order by total_spend,average_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased as 'products', 
round( 100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as "discount_rate"
from customer_behavior
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with cte as (select customer_id, previous_purchases,
case
	when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "Returning"
    else "Loyal"
 end as customer_segmentation
 from customer_behavior
 )
 select customer_segmentation, count(customer_segmentation) as 'Count of each segment' from cte
 group by customer_segmentation
 order by count(customer_segmentation) desc;
 
 -- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_behavior
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as revenue_contribution
from customer_behavior
group by age_group
order by revenue_contribution desc;

SELECT VERSION();
